###
POST https://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "rose",
  "dateOfBirth": "2000-1-1",
  "ssn": "029zxb",
  "gender": "male",
  "occupation": "xxx"
}

### 
Get http://localhost:3001/api/patients